"""Shared domain types -- node type constants and groupings.

This is the canonical leaf module for node type definitions.
Both ast/ and passes/ import from here. No upward dependencies.

Source of truth for node type IDs:
  frontend/packages/workflow/base/src/types/node-type.ts
"""

from __future__ import annotations

from enum import StrEnum




__all__ = [
    'NodeType',
    'START_NODE_ID', 'END_NODE_ID',
    'START_NODE_TYPE_ID', 'END_NODE_TYPE_ID',
    'LLM_NODE_TYPE_ID', 'CODE_NODE_TYPE_ID',
    'SUBWORKFLOW_NODE_TYPE_ID', 'VARIABLE_NODE_TYPE_ID',
    'QUESTION_NODE_TYPE_ID', 'INTENT_NODE_TYPE_ID',
    'IMAGE_GENERATE_NODE_TYPE_ID', 'IMAGE_CANVAS_NODE_TYPE_ID',
    'LTM_NODE_TYPE_ID', 'DATASET_SEARCH_NODE_TYPE_ID',
    'DATASET_WRITE_NODE_TYPE_ID', 'TEXT_PROCESS_NODE_TYPE_ID',
    'HTTP_NODE_TYPE_ID', 'SET_VARIABLE_NODE_TYPE_ID',
    'VARIABLE_ASSIGN_NODE_TYPE_ID', 'DATABASE_NODE_TYPE_ID',
    'DATABASE_UPDATE_NODE_TYPE_ID', 'DATABASE_QUERY_NODE_TYPE_ID',
    'DATABASE_DELETE_NODE_TYPE_ID', 'DATABASE_CREATE_NODE_TYPE_ID',
    'OUTPUT_NODE_TYPE_ID', 'INPUT_NODE_TYPE_ID', 'PLUGIN_NODE_TYPE_ID',
    'IF_NODE_TYPE_ID', 'LOOP_NODE_TYPE_ID', 'BATCH_NODE_TYPE_ID',
    'CONTINUE_NODE_TYPE_ID', 'BREAK_NODE_TYPE_ID',
    'VARIABLE_MERGE_NODE_TYPE_ID', 'TRIGGER_UPSERT_NODE_TYPE_ID',
    'TRIGGER_DELETE_NODE_TYPE_ID', 'TRIGGER_READ_NODE_TYPE_ID',
    'JSON_STRINGIFY_NODE_TYPE_ID', 'COMMENT_NODE_TYPE_ID',
    'QUERY_MESSAGE_LIST_NODE_TYPE_ID', 'CLEAR_CONTEXT_NODE_TYPE_ID',
    'CREATE_CONVERSATION_NODE_TYPE_ID', 'UPDATE_CONVERSATION_NODE_TYPE_ID',
    'DELETE_CONVERSATION_NODE_TYPE_ID', 'QUERY_CONVERSATION_LIST_NODE_TYPE_ID',
    'QUERY_CONVERSATION_HISTORY_NODE_TYPE_ID', 'CREATE_MESSAGE_NODE_TYPE_ID',
    'UPDATE_MESSAGE_NODE_TYPE_ID', 'DELETE_MESSAGE_NODE_TYPE_ID',
    'DATABASE_NODE_TYPE_IDS', 'COMPOSITE_NODE_TYPE_IDS',
    'LOOP_CONTROL_NODE_TYPE_IDS', 'CHAT_NODE_TYPE_IDS',
    'KNOWN_NODE_TYPE_IDS',
]

class NodeType(StrEnum):
    """Canonical Coze workflow node type IDs.

    Values match frontend StandardNodeType enum (node-type.ts).
    """
    START = '1'
    END = '2'
    LLM = '3'
    PLUGIN = '4'
    CODE = '5'
    DATASET_SEARCH = '6'
    IF = '8'
    SUBWORKFLOW = '9'
    VARIABLE = '11'
    DATABASE = '12'
    OUTPUT = '13'
    IMAGEFLOW = '14'
    TEXT_PROCESS = '15'
    IMAGE_GENERATE = '16'
    IMAGE_REFERENCE = '17'
    QUESTION = '18'
    BREAK = '19'
    SET_VARIABLE = '20'
    LOOP = '21'
    INTENT = '22'
    IMAGE_CANVAS = '23'
    SCENE_VARIABLE = '24'
    SCENE_CHAT = '25'
    LTM = '26'
    DATASET_WRITE = '27'
    BATCH = '28'
    CONTINUE = '29'
    INPUT = '30'
    COMMENT = '31'
    VARIABLE_MERGE = '32'
    TRIGGER_UPSERT = '34'
    TRIGGER_DELETE = '35'
    TRIGGER_READ = '36'
    QUERY_MESSAGE_LIST = '37'
    CLEAR_CONTEXT = '38'
    CREATE_CONVERSATION = '39'
    VARIABLE_ASSIGN = '40'
    DATABASE_UPDATE = '42'
    DATABASE_QUERY = '43'
    DATABASE_DELETE = '44'
    HTTP = '45'
    DATABASE_CREATE = '46'
    JSON_STRINGIFY = '58'
    UPDATE_CONVERSATION = '51'
    DELETE_CONVERSATION = '52'
    QUERY_CONVERSATION_LIST = '53'
    QUERY_CONVERSATION_HISTORY = '54'
    CREATE_MESSAGE = '55'
    UPDATE_MESSAGE = '56'
    DELETE_MESSAGE = '57'
    JSON_PARSER = '59'


# Canonical node IDs (canvas root markers)
START_NODE_ID = '100001'
END_NODE_ID = '900001'

# ── Node type ID aliases (prefer NodeType.X in new code) ──
START_NODE_TYPE_ID = NodeType.START
END_NODE_TYPE_ID = NodeType.END
LLM_NODE_TYPE_ID = NodeType.LLM
CODE_NODE_TYPE_ID = NodeType.CODE
SUBWORKFLOW_NODE_TYPE_ID = NodeType.SUBWORKFLOW
VARIABLE_NODE_TYPE_ID = NodeType.VARIABLE
QUESTION_NODE_TYPE_ID = NodeType.QUESTION
INTENT_NODE_TYPE_ID = NodeType.INTENT
IMAGE_GENERATE_NODE_TYPE_ID = NodeType.IMAGE_GENERATE
IMAGE_CANVAS_NODE_TYPE_ID = NodeType.IMAGE_CANVAS
LTM_NODE_TYPE_ID = NodeType.LTM
DATASET_SEARCH_NODE_TYPE_ID = NodeType.DATASET_SEARCH
DATASET_WRITE_NODE_TYPE_ID = NodeType.DATASET_WRITE
TEXT_PROCESS_NODE_TYPE_ID = NodeType.TEXT_PROCESS
HTTP_NODE_TYPE_ID = NodeType.HTTP
SET_VARIABLE_NODE_TYPE_ID = NodeType.SET_VARIABLE
VARIABLE_ASSIGN_NODE_TYPE_ID = NodeType.VARIABLE_ASSIGN
DATABASE_NODE_TYPE_ID = NodeType.DATABASE
DATABASE_UPDATE_NODE_TYPE_ID = NodeType.DATABASE_UPDATE
DATABASE_QUERY_NODE_TYPE_ID = NodeType.DATABASE_QUERY
DATABASE_DELETE_NODE_TYPE_ID = NodeType.DATABASE_DELETE
DATABASE_CREATE_NODE_TYPE_ID = NodeType.DATABASE_CREATE
OUTPUT_NODE_TYPE_ID = NodeType.OUTPUT
INPUT_NODE_TYPE_ID = NodeType.INPUT
PLUGIN_NODE_TYPE_ID = NodeType.PLUGIN
IF_NODE_TYPE_ID = NodeType.IF
LOOP_NODE_TYPE_ID = NodeType.LOOP
BATCH_NODE_TYPE_ID = NodeType.BATCH
CONTINUE_NODE_TYPE_ID = NodeType.CONTINUE
BREAK_NODE_TYPE_ID = NodeType.BREAK
VARIABLE_MERGE_NODE_TYPE_ID = NodeType.VARIABLE_MERGE
TRIGGER_UPSERT_NODE_TYPE_ID = NodeType.TRIGGER_UPSERT
TRIGGER_DELETE_NODE_TYPE_ID = NodeType.TRIGGER_DELETE
TRIGGER_READ_NODE_TYPE_ID = NodeType.TRIGGER_READ
JSON_STRINGIFY_NODE_TYPE_ID = NodeType.JSON_STRINGIFY
COMMENT_NODE_TYPE_ID = NodeType.COMMENT
QUERY_MESSAGE_LIST_NODE_TYPE_ID = NodeType.QUERY_MESSAGE_LIST
CLEAR_CONTEXT_NODE_TYPE_ID = NodeType.CLEAR_CONTEXT
CREATE_CONVERSATION_NODE_TYPE_ID = NodeType.CREATE_CONVERSATION
UPDATE_CONVERSATION_NODE_TYPE_ID = NodeType.UPDATE_CONVERSATION
DELETE_CONVERSATION_NODE_TYPE_ID = NodeType.DELETE_CONVERSATION
QUERY_CONVERSATION_LIST_NODE_TYPE_ID = NodeType.QUERY_CONVERSATION_LIST
QUERY_CONVERSATION_HISTORY_NODE_TYPE_ID = NodeType.QUERY_CONVERSATION_HISTORY
CREATE_MESSAGE_NODE_TYPE_ID = NodeType.CREATE_MESSAGE
UPDATE_MESSAGE_NODE_TYPE_ID = NodeType.UPDATE_MESSAGE
DELETE_MESSAGE_NODE_TYPE_ID = NodeType.DELETE_MESSAGE

# ── Node type groupings ──
DATABASE_NODE_TYPE_IDS = frozenset({
    DATABASE_NODE_TYPE_ID,
    DATABASE_UPDATE_NODE_TYPE_ID,
    DATABASE_QUERY_NODE_TYPE_ID,
    DATABASE_DELETE_NODE_TYPE_ID,
    DATABASE_CREATE_NODE_TYPE_ID,
})

COMPOSITE_NODE_TYPE_IDS = frozenset({
    IF_NODE_TYPE_ID,
    LOOP_NODE_TYPE_ID,
    BATCH_NODE_TYPE_ID,
})

LOOP_CONTROL_NODE_TYPE_IDS = frozenset({
    CONTINUE_NODE_TYPE_ID,
    BREAK_NODE_TYPE_ID,
})

CHAT_NODE_TYPE_IDS = frozenset({
    QUERY_MESSAGE_LIST_NODE_TYPE_ID,
    CLEAR_CONTEXT_NODE_TYPE_ID,
    CREATE_CONVERSATION_NODE_TYPE_ID,
    UPDATE_CONVERSATION_NODE_TYPE_ID,
    DELETE_CONVERSATION_NODE_TYPE_ID,
    QUERY_CONVERSATION_LIST_NODE_TYPE_ID,
    QUERY_CONVERSATION_HISTORY_NODE_TYPE_ID,
    CREATE_MESSAGE_NODE_TYPE_ID,
    UPDATE_MESSAGE_NODE_TYPE_ID,
    DELETE_MESSAGE_NODE_TYPE_ID,
})

# Derived from NodeType enum -- single source of truth
KNOWN_NODE_TYPE_IDS = frozenset(n.value for n in NodeType)
